apiVersion: batch/v1
kind: Job
metadata:
  name: db-create
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: rails
        image: localhost/rails:latest
        imagePullPolicy: Never
        command: 
          - bundle
          - exec
          - rails
          - db:create
        env:
          - name: RAILS_ENV
            value: development
          - name: DB_HOST
            value: postgresql-service
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: postgres
      restartPolicy: Never
