apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
spec:
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: localhost/rails:latest
        imagePullPolicy: Never
        command:
          - bundle
          - exec
        args:
          - unicorn -c /rails/config/unicorn.rb -E development

        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: RAILS_ENV
            value: development
          - name: DB_HOST
            value: postgresql-service