apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: PGDATA
            value: /var/lib/postgresql/data
        volumeMounts:
          - name: postgresdb-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresdb-storage
          persistentVolumeClaim:
            claimName: pvc-postgresql
